Logging Analytics Enhancements
oracle-quickstart/oci-observability-and-management pull request #29
Opened 2023-08-21 05:52 UTC by naikvenu

Support IDCS Identity domains
Remove Dynamic groups and Policies
Remove User creation
Remove Compartment Creation
Minor enhancements in the look and feel

2023-08-23 18:42 UTC, kgvarun requested changes
@naikvenu Added my comments inline.

2023-08-24 00:19 UTC, naikvenu commented on examples/oci-logging-analytics/schema.yaml
> -* Onboard Logging Analytics
Have changed the logic on this. Automatically determining if the LA is onboarded. If yes then it will skip.

data "oci_log_analytics_namespace" "this" {
    namespace = data.oci_identity_tenancy.this.name
}

resource "oci_log_analytics_namespace" "logging_analytics_namespace" {
  #Required
  count          = data.oci_log_analytics_namespace.this.is_onboarded == true ? 0 : 1
  compartment_id = local.tenancy_id
  is_onboarded   = true
  namespace      = data.oci_identity_tenancy.this.name
  depends_on     = [module.logging_analytics_quickstart, data.oci_log_analytics_namespace.this]
}

2023-08-24 00:20 UTC, naikvenu commented on examples/oci-logging-analytics/schema.yaml
> +      - existing_logging_analytics_group_name
The groups go inside IDCS domains. so i am not sure if this would work.

2023-08-24 00:22 UTC, naikvenu commented on examples/oci-logging-analytics/schema.yaml
>        - "no"
Just covering both options here. If 'no' then provided a prompt to add the IAM group name to use.
If 'yes' it will create a new group.
let me know if you just want to use exisiting group.

2023-09-06 17:10 UTC, kgvarun approved these changes

2023-09-06 17:10 UTC, merged